### ISSUE TITLE
Avoid adding global style

### ISSUE THREAD

**Issue by BrevAlessio** [surveyjs/surveyjs_vue_quickstart#18]
Hey, is it possibile to avoid having survey style (eg. Bootstrap) injected in my page at a global level? I'm trying to use `scoped` attribute but the result is the same: bootstrap style is affecting other application parts.

I could use an iframe but I would prefer to avoid that.

**Comment by tsv2013** [comment]
You can use another theme - default (https://surveyjs.io/Examples/Library?id=real-product-fit-market&platform=jQuery&theme=default) or modern (https://surveyjs.io/Examples/Library?id=real-product-fit-market&platform=jQuery&theme=modern).
