### ISSUE TITLE
Uncaught Error: Component survey is already registered

### ISSUE THREAD

**Issue by vaibhav6233m** [surveyjs/surveyjs_vue_quickstart#5]
I followed the steps given in the repository readme and only installed the dependencies without changing any code. Getting the following issue in console with a white blank screen on port 8080.

![image](https://user-images.githubusercontent.com/29979122/57059575-9b3ee380-6cd3-11e9-8b12-794605a2c7e3.png)

**Comment by tsv2013** [comment]
Unfortunaraly I've not managed to reproduce the issue. I've done exact the steps from readme file and got working site at the http://localhost:8080/ with clean console.
Can you provide us with any additional info?

**Comment by vaibhav6233m** [comment]
I just tried a fresh clone and everything seems to be working correctly without any issue.
Must be some stupid mistake on my part I guess. My apologies. Thank you for your inputs @tsv2013 .

**Comment by e-hop** [comment]
Happening on react's example
[Link](https://codesandbox.io/s/hj6i4?file=/src/SurveyCreatorComponent.jsx)
