### ISSUE TITLE
project too simple to know model usage

### ISSUE THREAD

**Issue by markoze** [surveyjs/surveyjs_vue_quickstart#8]
Please expand this project to include more often used cases in survey, like:

add model events "onValueChanged", "onCompleted"   - your "survey react quickstart" has them already;
also before creation and then dynamically changing some properties, like "title",  or adding conditional question in to existing survey

Currently project is too basic in my opinion.

**Comment by tsv2013** [comment]
This project shows SurveyJS Library/Creator integration into VueJS project.
Model properties are described in the documentation on our site https://surveyjs.io/Documentation/Library/ and live examples for all the supported frameworks can be found here - https://surveyjs.io/Examples/Library/?id=real-nps&platform=Vue

**Comment by markoze** [comment]
Thank you.
Indeed your documentation is really comprehensive. On the other hand, making project on par with react-quick-start would benefit it.
